name: gallery
version: 0.5.16+116
description: Maxeem Gallery shows beautiful, high-quality pictures from the Unsplash website
authors:
  - Max Shemetov <shemetov.career@gmail.com>
repository: https://github.com/maxeema/gallery

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=2.9.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  flutter_cupertino_localizations: ^1.0.1

  http: ^0.12.2
  transparent_image: ^1.0.0
  flutter_staggered_grid_view: ^0.3.2
  url_launcher: ^5.5.0
  package_info: ^0.4.3
  shared_preferences: ^0.5.10
  share: ^0.6.4+5
  fluttertoast: ^7.0.2
  flutter_hooks: ^0.13.2
  font_awesome_flutter: ^8.8.1
  photo_view: ^0.10.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: any
  mockito: ^4.1.1
  flutter_driver:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/
    - assets/icon.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font.
  fonts:
    - family: Caveat
      fonts:
        - asset: fonts/Caveat-Regular.ttf
    - family: JuliusSansOne
      fonts:
        - asset: fonts/JuliusSansOne-Regular.ttf
  #        weight: 400
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
